name: Windows Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      run: pip install matplotlib numpy pandas py-cpuinfo
    
    - name: Run tests and update benchmarks
      run: .\run_tests.bat

    - name: Pull latest changes
      run: git pull
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update benchmark results from GitHub Actions (Windows)"
        file_pattern: benchmark_results_windows_msvc/*
        add_options: -f